name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Setup key
      - name: Setup key
        run:
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # Deploy
      - name: Deploy
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . solin@${{ secrets.HOST }}:/var/www/blog.solin.cc
        working-directory: ./dist